name: Build and deploy Python app to Azure Web App - ai-document-assistance-anuj

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: ai-document-assistance-anuj
  AZURE_WEBAPP_PACKAGE_PATH: .

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build web app
        uses: azure/appservice-build@v2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BFC8F0B1EB764705885FE84E18F4ACEC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F0314DF39F6A4CC0BA21C6EF1E795B9A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2151E78D162C420B8147920FF4D3F623 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ai-document-assistance-anuj
          slot-name: Production
          package: .